name: Check generated examples
on:
  pull_request:
  push:

jobs:
  check-test-vectors:
    name: Ensure generated examples are up to date
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Check if test vectors are up to date
        run: |
          cd examples
          ./setup.sh
          ./inject-generated-content.sh --check
